# ---- Build stage ----
FROM golang:1.25.1-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o app main.go

# ---- Runtime stage ----
FROM alpine:3.20

WORKDIR /app

# Security best practice
RUN adduser -D appuser
USER appuser

COPY --from=builder /app/app ./app

EXPOSE 3000

CMD ["./app"]
